version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt

  build:
    commands:
      - echo Running Flask test...
      - python3 test_app.py

  post_build:
    commands:
      - echo Build and test completed successfully.

artifacts:
  files:
    - '**/*'
